version: '3.4'
services:
  playwright:
    container_name: PlaywrightIssueContainer
    ports:
      - '9323:9323'
    volumes:
      - playwright-report:/app/playwright-report
      - test-results:/app/test-results
     # - /tmp/.X11-unix:/tmp/.X11-unix
    environment:
      - CI
     # - DISPLAY=host.docker.internal:0
    build:
      context: .
      dockerfile: docker/Dockerfile
volumes:
  playwright-report:
  test-results:
